# -*- mode: yaml -*-

- name: install google chrome
  hosts: target
  tasks:
    - name: fetch public key
      get_url:
        url: https://dl.google.com/linux/linux_signing_key.pub
        dest: /tmp/linux_signing_key.pub

    - name: install public key
      become: true
      apt_key:
        file: /tmp/linux_signing_key.pub

    - name: install google chrome repository
      become: true
      apt_repository:
        repo: deb http://dl.google.com/linux/chrome/deb/ stable main

    - name: install google chrome
      become: true
      apt:
        name: google-chrome-stable
        update_cache: true
